/**
 * Test program #2: RC4-encrypted strings (no CRT, no plaintext in binary)
 *
 * Blobs are pre-encrypted with RC4 (key "s3cr3tK3y!") and stored as
 * raw hex bytes in .data. No plaintext strings exist in the binary.
 * DecryptStringRc4() decrypts each blob into a global buffer at runtime.
 *
 * Build: cl /Od /Zi /W3 /GS- /MT rc4_strings.c /Fe:rc4_strings.exe /link /RELEASE /DEBUG /ENTRY:Entry /SUBSYSTEM:CONSOLE /NODEFAULTLIB /INCREMENTAL:NO kernel32.lib
 *
 * To test with StringDecryptorPlugin:
 *   1. Open rc4_strings.exe in KernelFlirt
 *   2. Find DecryptStringRc4 — 5 calls with 3 args (RCX=blob, RDX=key, R8D=10)
 *   3. Result location = RAX, Encoding = ASCII
 */

#include <windows.h>

/* ---- RC4 ---- */

typedef struct {
    unsigned char S[256];
    int i, j;
} RC4_CTX;

__declspec(noinline) static void rc4_init(RC4_CTX* ctx, const unsigned char* key, int keylen)
{
    int i, j;
    for (i = 0; i < 256; i++) ctx->S[i] = (unsigned char)i;
    for (i = 0, j = 0; i < 256; i++) {
        j = (j + ctx->S[i] + key[i % keylen]) & 0xFF;
        unsigned char tmp = ctx->S[i];
        ctx->S[i] = ctx->S[j];
        ctx->S[j] = tmp;
    }
    ctx->i = 0;
    ctx->j = 0;
}

__declspec(noinline) static void rc4_crypt(RC4_CTX* ctx, unsigned char* data, int len)
{
    for (int n = 0; n < len; n++) {
        ctx->i = (ctx->i + 1) & 0xFF;
        ctx->j = (ctx->j + ctx->S[ctx->i]) & 0xFF;
        unsigned char tmp = ctx->S[ctx->i];
        ctx->S[ctx->i] = ctx->S[ctx->j];
        ctx->S[ctx->j] = tmp;
        data[n] ^= ctx->S[(ctx->S[ctx->i] + ctx->S[ctx->j]) & 0xFF];
    }
}

/* ---- Helpers (no CRT) ---- */

static int mystrlen(const char* s)
{
    int n = 0;
    while (s[n]) n++;
    return n;
}

static void mymemcpy(void* dst, const void* src, int n)
{
    char* d = (char*)dst;
    const char* s = (const char*)src;
    for (int i = 0; i < n; i++) d[i] = s[i];
}

static void Print(const char* msg)
{
    HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD written;
    WriteConsoleA(h, msg, (DWORD)mystrlen(msg), &written, NULL);
}

static void PrintLine(const char* prefix, const char* str)
{
    char buf[512];
    int i = 0;
    const char* p = prefix;
    while (*p && i < 500) buf[i++] = *p++;
    p = str;
    while (*p && i < 500) buf[i++] = *p++;
    buf[i++] = '\r'; buf[i++] = '\n'; buf[i] = '\0';
    Print(buf);
}

/* ---- Pre-encrypted blobs ----
 *
 * Generated by encrypting these strings with RC4 key "s3cr3tK3y!" (10 bytes):
 *   [0] "kernel32.dll"                       (12 bytes)
 *   [1] "NtQueryInformationProcess"           (25 bytes)
 *   [2] "C:\Windows\System32\calc.exe"        (28 bytes)
 *   [3] "Mozilla/5.0 (Windows NT 10.0)"       (29 bytes)
 *   [4] "SELECT * FROM users WHERE admin=1"   (33 bytes)
 *
 * Format: { length_lo, length_hi, encrypted_bytes... }
 *
 * Python to regenerate:
 *   from Crypto.Cipher import ARC4
 *   key = b"s3cr3tK3y!"
 *   for s in strings:
 *       ct = ARC4.new(key).encrypt(s.encode())
 *       blob = [len(s) & 0xFF, (len(s)>>8) & 0xFF] + list(ct)
 *       print("{" + ",".join(f"0x{b:02X}" for b in blob) + "}")
 */

/* "kernel32.dll" (12 bytes) */
static volatile unsigned char blob0[] = {
    0x0C, 0x00,
    0x00, 0xCF, 0xC1, 0x5B, 0x8B, 0xE7, 0xD7, 0xDD, 0xCF, 0x45, 0xAB, 0xC0
};
/* "NtQueryInformationProcess" (25 bytes) */
static volatile unsigned char blob1[] = {
    0x19, 0x00,
    0x25, 0xDE, 0xE2, 0x40, 0x8B, 0xF9, 0x9D, 0xA6, 0x8F, 0x47, 0xA8, 0xDE,
    0x15, 0xA2, 0x3F, 0xED, 0xF0, 0x32, 0x68, 0x0A, 0x48, 0x00, 0xB1, 0x4D,
    0x95
};
/* "C:\Windows\System32\calc.exe" (28 bytes) */
static volatile unsigned char blob2[] = {
    0x1C, 0x00,
    0x28, 0x90, 0xEF, 0x62, 0x87, 0xE5, 0x80, 0x80, 0x96, 0x52, 0x9B, 0xFF,
    0x01, 0xB0, 0x3F, 0xE1, 0xF2, 0x6F, 0x0A, 0x24, 0x44, 0x02, 0xB8, 0x5D,
    0xC8, 0x00, 0xCD, 0x97
};
/* "Mozilla/5.0 (Windows NT 10.0)" (29 bytes) */
static volatile unsigned char blob3[] = {
    0x1D, 0x00,
    0x26, 0xC5, 0xC9, 0x5C, 0x82, 0xE7, 0x85, 0xC0, 0xD4, 0x0F, 0xF7, 0x8C,
    0x50, 0x94, 0x22, 0xEA, 0xFB, 0x33, 0x4F, 0x0B, 0x07, 0x2D, 0x80, 0x1E,
    0xD7, 0x55, 0x9B, 0xC2, 0x73
};
/* "SELECT * FROM users WHERE admin=1" (33 bytes) */
static volatile unsigned char blob4[] = {
    0x21, 0x00,
    0x38, 0xEF, 0xFF, 0x70, 0xAD, 0xDF, 0xC4, 0xC5, 0xC1, 0x67, 0x95, 0xE3,
    0x35, 0xE3, 0x3E, 0xF7, 0xFA, 0x2E, 0x4B, 0x58, 0x70, 0x2B, 0x91, 0x6C,
    0xA3, 0x45, 0xD4, 0x96, 0x37, 0xBB, 0xCC, 0x30, 0xF8
};

/* Decrypted output buffer */
static volatile char g_decrypted[512];

/* RC4 key stored as bytes (no readable string in .rdata) */
static volatile unsigned char g_key[] = {
    0x73,0x33,0x63,0x72,0x33,0x74,0x4B,0x33,0x79,0x21  /* s3cr3tK3y! */
};

/* ---- Decrypt function (TARGET for the plugin) ---- */

__declspec(noinline) char* DecryptStringRc4(
    const volatile unsigned char* blob,
    const volatile unsigned char* key,
    int keylen)
{
    int len = blob[0] | (blob[1] << 8);
    if (len <= 0 || len > 500) {
        *(volatile char*)&g_decrypted[0] = '\0';
        return (char*)g_decrypted;
    }

    mymemcpy((void*)g_decrypted, (const void*)&blob[2], len);
    *(volatile char*)&g_decrypted[len] = '\0';

    RC4_CTX ctx;
    rc4_init(&ctx, (const unsigned char*)key, keylen);
    rc4_crypt(&ctx, (unsigned char*)g_decrypted, len);

    return (char*)g_decrypted;
}

/* ---- Entry point ---- */

void __stdcall Entry(void)
{
    Print("[*] RC4 String Decryptor Test\r\n\r\n");

    PrintLine("[1] ", DecryptStringRc4(blob0, g_key, 10));
    PrintLine("[2] ", DecryptStringRc4(blob1, g_key, 10));
    PrintLine("[3] ", DecryptStringRc4(blob2, g_key, 10));
    PrintLine("[4] ", DecryptStringRc4(blob3, g_key, 10));
    PrintLine("[5] ", DecryptStringRc4(blob4, g_key, 10));

    Print("\r\n[*] Done. 5 strings decrypted.\r\n");
    ExitProcess(0);
}
