/**
 * Test program #2: RC4-encrypted strings (no CRT, no plaintext in binary)
 *
 * Blobs are pre-encrypted with RC4 (key "s3cr3tK3y!") and stored as
 * raw hex bytes in .data. No plaintext strings exist in the binary.
 * DecryptStringRc4() decrypts each blob into a global buffer at runtime.
 *
 * Build: cl /Od /Zi /W3 /GS- /MT rc4_strings.c /Fe:rc4_strings.exe /link /RELEASE /DEBUG /ENTRY:Entry /SUBSYSTEM:CONSOLE /NODEFAULTLIB /INCREMENTAL:NO kernel32.lib
 *
 * To test with StringDecryptorPlugin:
 *   1. Open rc4_strings.exe in KernelFlirt
 *   2. Find DecryptStringRc4 — 5 calls with 3 args (RCX=blob, RDX=key, R8D=10)
 *   3. Result location = RAX, Encoding = ASCII
 */

#include <windows.h>

/* ---- RC4 ---- */

typedef struct {
    unsigned char S[256];
    int i, j;
} RC4_CTX;

__declspec(noinline) static void rc4_init(RC4_CTX* ctx, const unsigned char* key, int keylen)
{
    int i, j;
    for (i = 0; i < 256; i++) ctx->S[i] = (unsigned char)i;
    for (i = 0, j = 0; i < 256; i++) {
        j = (j + ctx->S[i] + key[i % keylen]) & 0xFF;
        unsigned char tmp = ctx->S[i];
        ctx->S[i] = ctx->S[j];
        ctx->S[j] = tmp;
    }
    ctx->i = 0;
    ctx->j = 0;
}

__declspec(noinline) static void rc4_crypt(RC4_CTX* ctx, unsigned char* data, int len)
{
    for (int n = 0; n < len; n++) {
        ctx->i = (ctx->i + 1) & 0xFF;
        ctx->j = (ctx->j + ctx->S[ctx->i]) & 0xFF;
        unsigned char tmp = ctx->S[ctx->i];
        ctx->S[ctx->i] = ctx->S[ctx->j];
        ctx->S[ctx->j] = tmp;
        data[n] ^= ctx->S[(ctx->S[ctx->i] + ctx->S[ctx->j]) & 0xFF];
    }
}

/* ---- Helpers (no CRT) ---- */

static int mystrlen(const char* s)
{
    int n = 0;
    while (s[n]) n++;
    return n;
}

static void mymemcpy(void* dst, const void* src, int n)
{
    char* d = (char*)dst;
    const char* s = (const char*)src;
    for (int i = 0; i < n; i++) d[i] = s[i];
}

static void Print(const char* msg)
{
    HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD written;
    WriteConsoleA(h, msg, (DWORD)mystrlen(msg), &written, NULL);
}

/* ---- Pre-encrypted blobs ----
 *
 * Generated by encrypting these strings with RC4 key "s3cr3tK3y!" (10 bytes):
 *   [0] "kernel32.dll"                       (12 bytes)
 *   [1] "NtQueryInformationProcess"           (25 bytes)
 *   [2] "C:\Windows\System32\calc.exe"        (27 bytes)
 *   [3] "Mozilla/5.0 (Windows NT 10.0)"       (29 bytes)
 *   [4] "SELECT * FROM users WHERE admin=1"   (33 bytes)
 *
 * Format: { length_lo, length_hi, encrypted_bytes... }
 *
 * Python to regenerate:
 *   from Crypto.Cipher import ARC4
 *   key = b"s3cr3tK3y!"
 *   for s in strings:
 *       ct = ARC4.new(key).encrypt(s.encode())
 *       blob = [len(s) & 0xFF, (len(s)>>8) & 0xFF] + list(ct)
 *       print("{" + ",".join(f"0x{b:02X}" for b in blob) + "}")
 */

/* "kernel32.dll" */
static volatile unsigned char blob0[] = {
    0x0C, 0x00,
    0xBB, 0xB2, 0xAF, 0xA5, 0x9E, 0xEB, 0xC7, 0x56, 0x89, 0x28, 0x13, 0xCE
};
/* "NtQueryInformationProcess" */
static volatile unsigned char blob1[] = {
    0x19, 0x00,
    0x9E, 0xA7, 0x8B, 0xB0, 0x92, 0xBE, 0x82, 0x10, 0xDE, 0x24, 0x0A, 0x83,
    0x6C, 0xB5, 0xDD, 0xD0, 0xEA, 0x07, 0x32, 0x32, 0x31, 0x19, 0x64, 0x1A,
    0x64
};
/* "C:\Windows\System32\calc.exe" */
static volatile unsigned char blob2[] = {
    0x1B, 0x00,
    0x93, 0x89, 0xE6, 0xA4, 0x82, 0xC9, 0xAF, 0x22, 0xC5, 0x39, 0x49, 0x87,
    0x04, 0xA8, 0xC6, 0xC5, 0xB7, 0x50, 0x42, 0x72, 0x06, 0x4A, 0x49, 0x03,
    0x67, 0x7C, 0x73
};
/* "Mozilla/5.0 (Windows NT 10.0)" */
static volatile unsigned char blob3[] = {
    0x1D, 0x00,
    0x9D, 0xBC, 0xB1, 0xA6, 0x8E, 0xCA, 0xA8, 0x7B, 0x84, 0x55, 0x4F, 0xD0,
    0x0E, 0xA0, 0xC6, 0xC5, 0xB7, 0x46, 0x56, 0x39, 0x06, 0x77, 0x3E, 0x7C,
    0x41, 0x58, 0x4C, 0x62, 0x67
};
/* "SELECT * FROM users WHERE admin=1" */
static volatile unsigned char blob4[] = {
    0x21, 0x00,
    0xA3, 0x92, 0x86, 0x80, 0x84, 0xC6, 0xC7, 0x56, 0x95, 0x06, 0x27, 0xA3,
    0x26, 0xD4, 0xCB, 0xCE, 0xAB, 0x56, 0x7B, 0x15, 0x2A, 0x73, 0x2B, 0x43,
    0x51, 0x14, 0x4D, 0x0A, 0x22, 0x6D, 0x29, 0x42, 0x49
};

/* Decrypted output buffer */
static volatile char g_decrypted[512];

/* RC4 key stored as bytes (no readable string in .rdata) */
static volatile unsigned char g_key[] = {
    0x73,0x33,0x63,0x72,0x33,0x74,0x4B,0x33,0x79,0x21  /* s3cr3tK3y! */
};

/* ---- Decrypt function (TARGET for the plugin) ---- */

__declspec(noinline) char* DecryptStringRc4(
    const volatile unsigned char* blob,
    const volatile unsigned char* key,
    int keylen)
{
    int len = blob[0] | (blob[1] << 8);
    if (len <= 0 || len > 500) {
        *(volatile char*)&g_decrypted[0] = '\0';
        return (char*)g_decrypted;
    }

    mymemcpy((void*)g_decrypted, (const void*)&blob[2], len);
    *(volatile char*)&g_decrypted[len] = '\0';

    RC4_CTX ctx;
    rc4_init(&ctx, (const unsigned char*)key, keylen);
    rc4_crypt(&ctx, (unsigned char*)g_decrypted, len);

    return (char*)g_decrypted;
}

/* ---- Entry point ---- */

void __stdcall Entry(void)
{
    Print("[*] RC4 String Decryptor Test\r\n\r\n");

    char* s1 = DecryptStringRc4(blob0, g_key, 10);
    Print("[1] "); Print(s1); Print("\r\n");

    char* s2 = DecryptStringRc4(blob1, g_key, 10);
    Print("[2] "); Print(s2); Print("\r\n");

    char* s3 = DecryptStringRc4(blob2, g_key, 10);
    Print("[3] "); Print(s3); Print("\r\n");

    char* s4 = DecryptStringRc4(blob3, g_key, 10);
    Print("[4] "); Print(s4); Print("\r\n");

    char* s5 = DecryptStringRc4(blob4, g_key, 10);
    Print("[5] "); Print(s5); Print("\r\n");

    Print("\r\n[*] Done. 5 strings decrypted.\r\n");
    ExitProcess(0);
}
