<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>KernelFlirt.UI</RootNamespace>
    <AssemblyName>KernelFlirt</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sdk\KernelFlirt.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Gee.External.Capstone" Version="2.3.0" />
    <PackageReference Include="Iced" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Themes\CDecompiler.xshd" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>


</Project>
